name: Ryan Brooks' blog
description: Technical musings and notes from a polyglot developer
url: https://www.ryanbrooks.co.uk
disqus_shortname: ryanbrooks
author_twitter: "@spikeheap"

safe: true
timezone: Europe/London
future: false
show_drafts: true

exclude: ['/vendor/']

excerpt_separator: <!--more-->
permalink: /posts/:year-:month-:day-:title/
encoding: utf-8

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"

assets:
  # compress:
  #   css: false | true | default - development: false, production: true
  #   js: false | true | default - development: false, production: true
  # cache: false | directory | default: .asset-cache
  digest: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
