name: Ryan Brooks' blog
description: Technical musings and notes from a polyglot developer
url: http://ryanbrooks.co.uk
disqus_shortname: ryanbrooks

safe: true
timezone: Europe/London
future: false
show_drafts: true

exclude: ['/vendor/']

excerpt_separator: <!--more-->
permalink: /posts/:year-:month-:day-:title/
encoding: utf-8

sass:
  sass_dir: _scss

kramdown:
  input: GFM


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
