version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build_and_deploy:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: ./bin/deploy.sh

workflows:
  deploy_site:
    jobs:
      - build_and_deploy
    filters:
      branches:
        only: main