name: Build and deploy site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Set git user
      run: |
        git config --global user.email "ryan@slatehorse.com"
        git config --global user.name "Deployment Bot"
    - run: ./bin/deploy.sh
      env:
        CI: true